react-app/package-lock.json, react-app/package.json, react-app/src/App.jsx, react-app/src/Auth.jsx, react-app/src/Home.jsx, react-app/src/Login.jsx
Implemented Auth0 Login Capabilities
=> Gustavo isturiz

README.md
=> Working on documentation 

react-app/package-lock.json, react-app/package.json, react-app/src/Workspace_Card.jsx, react-app/src/tests/Workspace.spec.js, react-app/src/tests/Workspace_Card.spec.js
=> Workspace and Workspace_Card testing

react-app/.env, react-app/src/Onboarding.jsx
=> fixed merge issues and button is not looooonnnnnng anymore

react-app/src/Components/RecogModal/RecogModal.jsx, react-app/src/landing/Header.js
Added the cancel button to the modal and styled it to the left as per hi fidelity.
X cancel button is present
- [X ] New feature (non-breaking change which adds functionality)
=> added functioning cancel button provided by UX to Modal

react-app/src/Workspace_Card.jsx, react-app/yarn.lock
=> added our bg graident to workspace

react-app/.env, react-app/src/Onboarding.jsx, react-app/src/store/reducers/user-reducer.js
Fixes #  Lack of user feedback when onboarding
Users are now redirected to the profile component.
=> Onboarding redirect fix

react-app/package.json, react-app/src/Components/Profile/RecognitionCard.jsx, react-app/src/Components/RecogModal/RecogModal.jsx, react-app/yarn.lock
PR had improperly resolved merge conflicts, The feature was also already implemented on staging.
=> Revert "added moment to have clearer time data displaying"

react-app/src/App.jsx, react-app/src/Components/Auth/Login.jsx, react-app/src/Components/Auth/ProtectedRoute.jsx, react-app/src/Components/Profile/Profile.jsx, react-app/src/Components/RecogModal/RecogModal.jsx, react-app/src/store/reducers/user-reducer.js
=> 🔧 fixed the profile updating, fixed timestamps

react-app/src/App.jsx, react-app/src/Components/Auth/Login.jsx, react-app/src/Components/Profile/Profile.jsx, react-app/src/Components/Profile/RecognitionCard.jsx, react-app/src/Components/Profile/index.js, react-app/src/utils/auth.js
adds the ability to visit peer profile from frontend
=> 👥 users can now access profile of other users by visiting /profile/:id

react-app/src/Onboarding.jsx
=> made onboarding page responsive

react-app/src/landing/Footer.js, react-app/src/landing/Header.js, react-app/src/landing/Nav.js
=> changed some text and nav order per UX

react-app/src/Components/Profile/Profile.jsx, react-app/src/Components/Profile/RecognitionCard.jsx, react-app/src/Components/sideBar/Sidebar.jsx
=> fixed responsiveness on profile page

react-app/src/Components/RecogModal/RecogModal.jsx, react-app/src/Workspace_Card.jsx
working on workspace responsiveness further.
=> reponsivizing the workspace delete

react-app/src/Components/Feed/Comment.jsx, react-app/src/Components/Profile/RecognitionCard.jsx, react-app/src/store/actions/feed-actions.js, react-app/src/store/reducers/feed-reducer.js
=> connects delete events

react-app/src/Components/RecogModal/RecogModal.jsx
=> added alert to recog modal

src/App.jsx, src/SCSS/abstracts/_variables.scss, src/SCSS/layout/sidenav.scss, src/SCSS/main.scss, src/SCSS/pages/_adminDashboard.scss, src/components/AdminDashboard/Activity.jsx, src/components/AdminDashboard/AdminDashboard.jsx, src/components/AdminDashboard/Reports.jsx, src/components/AdminDashboard/Teams.jsx, src/components/Onboarding.jsx, src/components/Onboarding/S6AllDone.jsx
- [x ] My changes generate no new warnings
=> Admin dashboard

src/SCSS/components/_landing-sidebar.scss, src/SCSS/main.scss, src/SCSS/pages/_landing.scss, src/components/Landing/DidYouKnow.jsx, src/components/Landing/EnterEmail.jsx, src/components/Landing/Footer.jsx, src/components/Landing/HamburgerMenu.jsx, src/components/Landing/Main.jsx, src/components/Landing/Nav.jsx, src/components/Onboarding/S2CreateAccount.jsx, src/components/Onboarding/S5AccountCustomization.jsx
=> fixed links on landing page and added a hamburger menu to the landing page

src/App.jsx, src/SCSS/main.scss, src/SCSS/pages/_userUpload.scss, src/components/UserUpload/BulkOrSingle.jsx, src/components/UserUpload/BulkUser.jsx, src/components/UserUpload/SingleUser.jsx, src/components/UserUpload/UserUpload.jsx, src/components/Workspace/index.jsx
=> Dashboard add users

src/SCSS/components/_landing-sidebar.scss, src/components/Landing/EnterEmail.jsx, src/components/Landing/Main.jsx
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Complete, but not tested (may need new tests)
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
- [x ] There are no merge conflicts
=> Link fixes

src/SCSS/pages/_adminDashboard.scss, src/components/AdminDashboard/AdminDashboard.jsx, src/components/AdminDashboard/Reports.jsx
Co-authored-by: vtellez1 <vanessatellez45@gmail.com>
Co-authored-by: emilybruner <bruner.emilym@gmail.com>
Co-authored-by: Hail91 <aarongillies88@gmail.com>
Co-authored-by: AndrewMaddocks <andrewmadd@icloud.com>
=> set up architecture for reports page

src/components/Onboarding/S4CUserUpload.jsx, src/components/UserUpload/BulkUser.jsx
Co-authored-by: vtellez1 <vanessatellez45@gmail.com>
Co-authored-by: ackers93 <andrew.ackers@gmail.com>
Co-authored-by: AndrewMaddocks <andrewmadd@icloud.com>
=> fixed issue wehre data from backend wasn't being displayed

src/SCSS/pages/_adminDashboard.scss, src/components/AdminDashboard/Reports.jsx
=> Dashboard reports linegraph

src/SCSS/pages/_profile.scss, src/components/Profile/Profile.jsx, src/components/Profile/RecognitionCard.jsx
Co-authored-by: ackers93 <andrew.ackers@gmail.com>
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] Complete, tested, ready to review and merge
=> fixed delete bug

src/SCSS/components/_feedSideBar.scss, src/SCSS/components/_mostRecog.scss, src/SCSS/pages/_adminDashboard.scss, src/SCSS/pages/_reports.scss, src/components/AdminDashboard/AdminDashboard.jsx, src/components/AdminDashboard/Reports.jsx, src/components/AdminDashboard/reports/LeadershipBoard.jsx, src/components/AdminDashboard/reports/TotalRecogGraph.jsx, src/components/FeedSideBar/FeedRecognition.jsx, src/components/FeedSideBar/index.jsx, src/components/Workspace/index.jsx
=> Minor styling fixes

src/SCSS/components/_feedSideBar.scss, src/components/FeedSideBar/FeedRecognition.jsx
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] Complete, but not tested (may need new tests)
=> feed bar edits

src/SCSS/components/_buttons.scss, src/components/RecogModal/index.jsx
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Complete, but not tested (may need new tests)
=> finished rec confirmation modal

src/components/AdminTeams/CreateTeam.jsx
=> testing pull request

src/SCSS/components/_modal.scss, src/SCSS/components/_reactionModel.scss, src/SCSS/pages/_profile.scss, src/components/AdminTeams/Member.jsx, src/components/AdminTeams/OrganizationHome.jsx, src/components/AdminTeams/TeamMemberList.jsx, src/components/EndUserDashboard/EndUserDashboard.jsx, src/components/Feed/CommentButton.jsx, src/components/Feed/ReactionButton.jsx, src/components/FeedSideBar/Activity.jsx, src/components/FeedSideBar/Badges.jsx, src/components/FeedSideBar/FeedRecognition.jsx, src/components/FeedSideBar/ProfileModal.jsx, src/components/FeedSideBar/ReactionModal.jsx, src/components/Onboarding/S5AccountCustomization.jsx, src/components/Profile/Profile.jsx, src/components/Profile/ProfileTeamList.jsx, src/components/Profile/RecognitionCard.jsx, src/components/SideBar/index.jsx
I fixed problems with the reaction modal
=> Fix end user dashboard

src/components/AdminTeams/Member.jsx, src/components/AdminTeams/TeamMemberList.jsx, src/components/Profile/Profile.jsx, src/components/Profile/RecognitionCard.jsx
Co-authored-by: JossWritesCode <joscelynrose@gmail.com>
=> corrected issue with user type being undefined in member component

src/SCSS/components/_deleteModal.scss, src/SCSS/layout/_footer.scss, src/components/AdminTeams/CreateTeam.jsx, src/components/AdminTeams/DeleteModal.jsx, src/components/AdminTeams/Member.jsx, src/components/AdminTeams/OrgEmployees.jsx, src/components/Onboarding/S4AUserUpload.jsx, src/components/Profile/ProfileTeamList.jsx, src/components/Profile/RecognitionCard.jsx
=> Fixing confirmation modal

src/components/Profile/ProfileTeamList.jsx
=> Fixed spacing
